### ISSUE TITLE
Improve plot appearance

### ISSUE THREAD

**Issue by anebz** [anebz/boulder#22]
The plots don't look good on small screens: read Streamlit design guide [part 1](https://blog.streamlit.io/designing-streamlit-apps/) and [part 2](https://blog.streamlit.io/designing-streamlit-apps-for-the-user-part-ii/). Maybe we'll have to use another plot library?

Guides read, did some improvements but there was nothing on plots

Somehow color code columns (time ranges) with weather status? green:sunny, yellow:cloud, orange:rain, red:thunderstorm

`st.plotly_chart(plot_data(givendaydf), width=800)` ?

**Comment by AnglinaBhambra** [comment]
@anebz Would this solve the problem?
https://discuss.streamlit.io/t/plotly-not-responsive-mobile-screen/2731/2

**Comment by anebz** [comment]
> @anebz Would this solve the problem?
> https://discuss.streamlit.io/t/plotly-not-responsive-mobile-screen/2731/2

Yes this makes the plot narrower, which in mobile makes it even narrower. I don't think our plots need to be so sophisticated with all the cool thing that plotly gives us, a simple plot is enough. We'll have to investigate a simple plot that lets us plot 2 things (occupancy and temperature), and maybe also a vertical bar with weather status

**Comment by AnglinaBhambra** [comment]
I've made changes so that you can use a line plot with 2 lines.
For the colour changing - what do you think about this: https://altair-viz.github.io/user_guide/customization.html#encoding ?

It would mean that the plot isn't a simple line chart though, so I'm not sure how it would look on small screens.
Let me know how the modified line chart looks - then I will try with Altair.

**Comment by anebz** [comment]
> I've made changes so that you can use a line plot with 2 lines.
> For the colour changing - what do you think about this: https://altair-viz.github.io/user_guide/customization.html#encoding ?
> 
> It would mean that the plot isn't a simple line chart though, so I'm not sure how it would look on small screens.
> Let me know how the modified line chart looks - then I will try with Altair.

Can you check and paste here how the plots look? you can run the app.py file right? I gave you the credentials and all the keys? 🤔 if I didn't, let me know and I'll resend

**Comment by AnglinaBhambra** [comment]
<img width="714" alt="Screenshot 2021-08-31 at 08 37 07" src="https://user-images.githubusercontent.com/35236308/131462403-593d645a-563e-4b52-94dd-c8e415205413.png">
 (Sorry it's not in dark mode haha)
 
 Yes, but I thought it would be more useful to see what it looks like on a smaller screen.

**Comment by anebz** [comment]
Improve website layout: https://docs.streamlit.io/library/api-reference#layouts-and-containers
