### ISSUE TITLE
Add Berlin MagicMountain gym

### ISSUE THREAD

**Issue by anebz** [anebz/boulder#25]
https://www.magicmountain.de/preise/#Besucheranzahl

* Add url and regex scraping code in `capture-data/web_scrape.py`
* Add try/excepts so that the code doesn't crash in any condition

**Comment by AnjaTRPES** [comment]
another weird thing: I pulled the 'occupied' number every 15 mintues yesterday for a bit, observing that it rose steadily until 21h42 (that's when I stopped recording, will record today completly). Checking now the occupancy this morning (before opening!) gives me 30 (though in agreement with what the counter looks like on the website). I suspect they only update it once they open -> will check how it looks at 10am.

**Comment by anebz** [comment]
That's great Anja! You're super fast 😱

With the other gyms, if there's people waiting, we just say that it's 110% full for instance. But if the Berlin ones don't have a number for waiting then we will only record until 100% capacity. 

About nighttime, yeah some gyms don't set the number to 0 at night. We just know that they close at 23, open at 7 and we record during those times. We might need to use different opening times for this gym, and only record from 10 until they close
